const GetLabels = (labelName, lang) => {
	let labels = [
		{ labelName: "start", lang: "en", value: "BEGIN"},
		{ labelName: "start", lang: "cn", value: ""},
		{ labelName: "restart", lang: "en", value: "Restart"},
		{ labelName: "restart", lang: "cn", value: ""},
		{ labelName: "quit", lang: "en", value: "Quit"},
		{ labelName: "quit", lang: "cn", value: ""},
		{ labelName: "language", lang: "en", value: "Language"},
		{ labelName: "language", lang: "cn", value: ""},
		{ labelName: "stage1", lang: "en", value: "STAGE ONE"},
		{ labelName: "stage1", lang: "cn", value: ""},
		{ labelName: "stage2", lang: "en", value: "STAGE TWO"},
		{ labelName: "stage2", lang: "cn", value: ""},
		{ labelName: "stage3", lang: "en", value: "STAGE THREE"},
		{ labelName: "stage3", lang: "cn", value: ""},
		{ labelName: "stage4", lang: "en", value: "STAGE FOUR"},
		{ labelName: "stage4", lang: "cn", value: ""},
		{ labelName: "stage5", lang: "en", value: "STAGE FIVE"},
		{ labelName: "stage5", lang: "cn", value: ""},	
		{ labelName: "opponent1", lang: "en", value: "LITTLE GRASS"},
		{ labelName: "opponent1", lang: "cn", value: ""},
		{ labelName: "opponent2", lang: "en", value: "CHANEL"},
		{ labelName: "opponent2", lang: "cn", value: "CHANEL"},
		{ labelName: "opponent3", lang: "en", value: "LULU"},
		{ labelName: "opponent3", lang: "cn", value: ""},
		{ labelName: "opponent4", lang: "en", value: "GONGSUN LAN"},
		{ labelName: "opponent4", lang: "cn", value: ""},
		{ labelName: "opponent5", lang: "en", value: "BIG SISTER SPRING"},
		{ labelName: "opponent5", lang: "cn", value: ""},	
		{ labelName: "guess", lang: "en", value: "Guess"},
		{ labelName: "guess", lang: "cn", value: ""},	
		{ labelName: "openup", lang: "en", value: "Open Up!"},
		{ labelName: "openup", lang: "cn", value: ""},
		{ labelName: "1s", lang: "en", value: "Ones"},
		{ labelName: "1s", lang: "cn", value: ""},
		{ labelName: "2s", lang: "en", value: "Twos"},
		{ labelName: "2s", lang: "cn", value: ""},
		{ labelName: "3s", lang: "en", value: "Threes"},
		{ labelName: "3s", lang: "cn", value: ""},
		{ labelName: "4s", lang: "en", value: "Fours"},
		{ labelName: "4s", lang: "cn", value: ""},
		{ labelName: "5s", lang: "en", value: "Fives"},
		{ labelName: "5s", lang: "cn", value: ""},
		{ labelName: "6s", lang: "en", value: "Sixes"},
		{ labelName: "6s", lang: "cn", value: ""},	
		{ labelName: "1dice", lang: "en", value: "One"},
		{ labelName: "1dice", lang: "cn", value: ""},
		{ labelName: "2dice", lang: "en", value: "Two"},
		{ labelName: "2dice", lang: "cn", value: ""},
		{ labelName: "3dice", lang: "en", value: "Three"},
		{ labelName: "3dice", lang: "cn", value: ""},
		{ labelName: "4dice", lang: "en", value: "Four"},
		{ labelName: "4dice", lang: "cn", value: ""},
		{ labelName: "5dice", lang: "en", value: "Five"},
		{ labelName: "5dice", lang: "cn", value: ""},
		{ labelName: "6dice", lang: "en", value: "Six"},
		{ labelName: "6dice", lang: "cn", value: ""},	
		{ labelName: "7dice", lang: "en", value: "Seven"},
		{ labelName: "7dice", lang: "cn", value: ""},
		{ labelName: "8dice", lang: "en", value: "Eight"},
		{ labelName: "8dice", lang: "cn", value: ""},
		{ labelName: "9dice", lang: "en", value: "Nine"},
		{ labelName: "9dice", lang: "cn", value: ""},
		{ labelName: "10dice", lang: "en", value: "Ten"},
		{ labelName: "10dice", lang: "cn", value: ""},	
		{ labelName: "", lang: "", value: ""}
	];

	let match = labels.filter((x)=> { return (x.labelName == labelName && x.lang == lang); });

	if (match.length == 0) return "";
	return match[0].value;
}

export default GetLabels;	