const GetPhrases = (personality, phraseName, lang) => {
	let phrases = [
		{ personality: 1, phraseName: "intro", lang: "en", value: "Hello, I'm Little Grass. Please go easy on me!"},
		{ personality: 1, phraseName: "intro", lang: "cn", value: "你好, 我是小草. 请高抬贵手!"},
		{ personality: 1, phraseName: "intro", lang: "en", value: "Hello, I'm Little Grass. I'm new at this. Pease show me the ropes!"},
		{ personality: 1, phraseName: "intro", lang: "cn", value: "你好, 我是小草. 我对这游戏不是很熟. 请多指教!"},
		{ personality: 2, phraseName: "intro", lang: "en", value: "My name is Chanel. Let's play!"},
		{ personality: 2, phraseName: "intro", lang: "cn", value: "我叫 Chanel. 咱们来玩一把!"},
		{ personality: 2, phraseName: "intro", lang: "en", value: "I'm Chanel. Are you familiar with this game?"},
		{ personality: 2, phraseName: "intro", lang: "cn", value: "我是 Chanel. 你会玩吗?"},
		{ personality: 3, phraseName: "intro", lang: "en", value: "Hi handsome! Please call me Lulu. Shall we begin?"},
		{ personality: 3, phraseName: "intro", lang: "cn", value: "帅哥! 请叫我鹿鹿. 我们开始好吗?"},
		{ personality: 3, phraseName: "intro", lang: "en", value: "How are you, handsome? I'm Lulu. Let's play!"},
		{ personality: 3, phraseName: "intro", lang: "cn", value: "你好吗,帅哥? 我是鹿鹿. 咱们来玩一把!"},
		{ personality: 4, phraseName: "intro", lang: "en", value: "How do you do? I'm happy to meet you. I am Gongsun Lan."},
		{ personality: 4, phraseName: "intro", lang: "cn", value: "你好吗? 很高兴认识你. 我是公孙蓝."},
		{ personality: 4, phraseName: "intro", lang: "en", value: "Welcome! Nice to meet you. I am Gongsun Lan, and I will be your opponent this round."},
		{ personality: 4, phraseName: "intro", lang: "cn", value: "欢迎! 幸会幸会. 我是公孙蓝, 我是你的对手."},
		{ personality: 5, phraseName: "intro", lang: "en", value: "Hey, I'm Big Sister Spring. Are you here to play?"},
		{ personality: 5, phraseName: "intro", lang: "cn", value: "嘿, 老娘是春姐. 来玩的吗?"},
		{ personality: 5, phraseName: "intro", lang: "en", value: "I'm the famous Big Sister Spring. You want to play? Let's go!"},
		{ personality: 5, phraseName: "intro", lang: "cn", value: "我是鼎鼎大名的春姐. 想玩是吗? 放马过来!"},
		{ personality: 1, phraseName: "newround", lang: "en", value: "I'm so excited. Let's start!"},
		{ personality: 1, phraseName: "newround", lang: "cn", value: "好兴奋! 开始吧!"},
		{ personality: 1, phraseName: "newround", lang: "en", value: "Please go slow!"},
		{ personality: 1, phraseName: "newround", lang: "cn", value: "慢点哦!"},
		{ personality: 2, phraseName: "newround", lang: "en", value: "Shall we begin?"},
		{ personality: 2, phraseName: "newround", lang: "cn", value: "能开始了吗?"},
		{ personality: 2, phraseName: "newround", lang: "en", value: "Come, let's play!"},
		{ personality: 2, phraseName: "newround", lang: "cn", value: "来来 咱们玩吧!"},
		{ personality: 3, phraseName: "newround", lang: "en", value: "Darling, let's begin."},
		{ personality: 3, phraseName: "newround", lang: "cn", value: "亲爱的 开始了!"},
		{ personality: 3, phraseName: "newround", lang: "en", value: "Honey, let's shake... the dice!"},
		{ personality: 3, phraseName: "newround", lang: "cn", value: "亲爱的 我们摇摇... 骰子!"},
		{ personality: 4, phraseName: "newround", lang: "en", value: "Please shake the dice!"},
		{ personality: 4, phraseName: "newround", lang: "cn", value: "请摇摇骰子!"},
		{ personality: 4, phraseName: "newround", lang: "en", value: "Let's start over. Please!"},
		{ personality: 4, phraseName: "newround", lang: "cn", value: "从头开始. 请!"},
		{ personality: 5, phraseName: "newround", lang: "en", value: "Why so slow? Shake the damn dice!"},
		{ personality: 5, phraseName: "newround", lang: "cn", value: "干嘛那么慢?摇啊!"},
		{ personality: 5, phraseName: "newround", lang: "en", value: "Are you ready to lose? Let's go!"},
		{ personality: 5, phraseName: "newround", lang: "cn", value: "输得起吗? 那就来啊!"},
		{ personality: 1, phraseName: "doubt", lang: "en", value: "Are we supposed to play like that?"},
		{ personality: 1, phraseName: "doubt", lang: "cn", value: "是这样玩的吗?"},
		{ personality: 1, phraseName: "doubt", lang: "en", value: "Let me think..."},
		{ personality: 1, phraseName: "doubt", lang: "cn", value: "我想想哦..."},
		{ personality: 2, phraseName: "doubt", lang: "en", value: "Are you sure about this?"},
		{ personality: 2, phraseName: "doubt", lang: "cn", value: "确定?"},
		{ personality: 2, phraseName: "doubt", lang: "en", value: "That is an odd way to play..."},
		{ personality: 2, phraseName: "doubt", lang: "cn", value: "这玩法挺奇怪的..."},
		{ personality: 3, phraseName: "doubt", lang: "en", value: "Handsome, are you sure?"},
		{ personality: 3, phraseName: "doubt", lang: "cn", value: "帅哥 你来真的吗?"},
		{ personality: 3, phraseName: "doubt", lang: "en", value: "Darling, your moves are strange!"},
		{ personality: 3, phraseName: "doubt", lang: "cn", value: "亲爱的 我觉得你有点不对劲儿!"},
		{ personality: 4, phraseName: "doubt", lang: "en", value: "Is that what you really want to do?"},
		{ personality: 4, phraseName: "doubt", lang: "cn", value: "你真想那么做?"},
		{ personality: 4, phraseName: "doubt", lang: "en", value: "Interesting, interesting!"},
		{ personality: 4, phraseName: "doubt", lang: "cn", value: "有意思, 有意思!"},
		{ personality: 5, phraseName: "doubt", lang: "en", value: "Do you know how to play or not?!"},
		{ personality: 5, phraseName: "doubt", lang: "cn", value: "你到底会不会玩的?!"},
		{ personality: 5, phraseName: "doubt", lang: "en", value: "Are you crazy?"},
		{ personality: 5, phraseName: "doubt", lang: "cn", value: "你疯了?"},
		{ personality: 1, phraseName: "myturn", lang: "en", value: "I think it's my turn."},
		{ personality: 1, phraseName: "myturn", lang: "cn", value: "好像轮到我了"},
		{ personality: 1, phraseName: "myturn", lang: "en", value: "I should make a decision... "},
		{ personality: 1, phraseName: "myturn", lang: "cn", value: "该我来了..."},
		{ personality: 2, phraseName: "myturn", lang: "en", value: "Oooh. My turn!"},
		{ personality: 2, phraseName: "myturn", lang: "cn", value: "哦 到我了!"},
		{ personality: 2, phraseName: "myturn", lang: "en", value: "Give me a moment. I need to think..."},
		{ personality: 2, phraseName: "myturn", lang: "cn", value: "让我想想..."},
		{ personality: 3, phraseName: "myturn", lang: "en", value: "Darling, I'm taking my turn now!"},
		{ personality: 3, phraseName: "myturn", lang: "cn", value: "亲爱的 我来了!"},
		{ personality: 3, phraseName: "myturn", lang: "en", value: "It's my turn, handsome!"},
		{ personality: 3, phraseName: "myturn", lang: "cn", value: "到我了, 帅哥!"},
		{ personality: 4, phraseName: "myturn", lang: "en", value: "Let me see..."},
		{ personality: 4, phraseName: "myturn", lang: "cn", value: "啊..."},
		{ personality: 4, phraseName: "myturn", lang: "en", value: "What should I do?"},
		{ personality: 4, phraseName: "myturn", lang: "cn", value: "该怎么做呢?"},
		{ personality: 5, phraseName: "myturn", lang: "en", value: "Hmph! I'm gonna make a move!"},
		{ personality: 5, phraseName: "myturn", lang: "cn", value: "哦! 老娘来了!"},
		{ personality: 5, phraseName: "myturn", lang: "en", value: "My turn now. Guess or open up?"},
		{ personality: 5, phraseName: "myturn", lang: "cn", value: "到我了 猜呢... 开呢...?"},	
		{ personality: 1, phraseName: "yourturn", lang: "en", value: "It's your turn, right?"},
		{ personality: 1, phraseName: "yourturn", lang: "cn", value: "到你了,对吗?"},
		{ personality: 1, phraseName: "yourturn", lang: "en", value: "Are you going to make a guess, or open up?"},
		{ personality: 1, phraseName: "yourturn", lang: "cn", value: "你猜呢,还是开?"},
		{ personality: 2, phraseName: "yourturn", lang: "en", value: "It's your turn!"},
		{ personality: 2, phraseName: "yourturn", lang: "cn", value: "到你了!"},
		{ personality: 2, phraseName: "yourturn", lang: "en", value: "Time for your move!"},
		{ personality: 2, phraseName: "yourturn", lang: "cn", value: "该你了!"},
		{ personality: 3, phraseName: "yourturn", lang: "en", value: "Handsome, what are you going to do?"},
		{ personality: 3, phraseName: "yourturn", lang: "cn", value: "帅哥 想怎么做?"},
		{ personality: 3, phraseName: "yourturn", lang: "en", value: "Baby, please make your move!"},
		{ personality: 3, phraseName: "yourturn", lang: "cn", value: "宝贝 请做决定!"},
		{ personality: 4, phraseName: "yourturn", lang: "en", value: "Your turn. Please!"},
		{ personality: 4, phraseName: "yourturn", lang: "cn", value: "该你了, 请!"},
		{ personality: 4, phraseName: "yourturn", lang: "en", value: "What do you think you should do?"},
		{ personality: 4, phraseName: "yourturn", lang: "cn", value: "你觉得该怎么做?"},
		{ personality: 5, phraseName: "yourturn", lang: "en", value: "Hurry up and make a move!"},
		{ personality: 5, phraseName: "yourturn", lang: "cn", value: "快点!"},
		{ personality: 5, phraseName: "yourturn", lang: "en", value: "Damn kid, it's your turn!"},
		{ personality: 5, phraseName: "yourturn", lang: "cn", value: "臭小子 该你了!"},	
		{ personality: 1, phraseName: "guess", lang: "en", value: "Let me see... I guess"},
		{ personality: 1, phraseName: "guess", lang: "cn", value: "我想想... 我猜..."},
		{ personality: 1, phraseName: "guess", lang: "en", value: "I'm guessing..."},
		{ personality: 1, phraseName: "guess", lang: "cn", value: "我在想... 我猜..."},
		{ personality: 2, phraseName: "guess", lang: "en", value: "Let me guess..."},
		{ personality: 2, phraseName: "guess", lang: "cn", value: "让我猜猜..."},
		{ personality: 2, phraseName: "guess", lang: "en", value: "I'm going to guess!"},
		{ personality: 2, phraseName: "guess", lang: "cn", value: "我来猜!"},
		{ personality: 3, phraseName: "guess", lang: "en", value: "I guess..."},
		{ personality: 3, phraseName: "guess", lang: "cn", value: "我猜..."},
		{ personality: 3, phraseName: "guess", lang: "en", value: "I think..."},
		{ personality: 3, phraseName: "guess", lang: "cn", value: "我想..."},
		{ personality: 4, phraseName: "guess", lang: "en", value: "Interesting..."},
		{ personality: 4, phraseName: "guess", lang: "cn", value: "有意思..."},
		{ personality: 4, phraseName: "guess", lang: "en", value: "This is my guess."},
		{ personality: 4, phraseName: "guess", lang: "cn", value: "我来猜了"},
		{ personality: 5, phraseName: "guess", lang: "en", value: "You can't fool m!"},
		{ personality: 5, phraseName: "guess", lang: "cn", value: "你骗不了我!"},
		{ personality: 5, phraseName: "guess", lang: "en", value: "Damn!"},
		{ personality: 5, phraseName: "guess", lang: "cn", value: "他妈的!"},
		{ personality: 1, phraseName: "openup", lang: "en", value: "Can you show me your dice?"},
		{ personality: 1, phraseName: "openup", lang: "cn", value: "能开给我看吗?"},
		{ personality: 1, phraseName: "openup", lang: "en", value: "I think we should open up!"},
		{ personality: 1, phraseName: "openup", lang: "cn", value: "我想我们开吧!"},
		{ personality: 2, phraseName: "openup", lang: "en", value: "Time to open up..."},
		{ personality: 2, phraseName: "openup", lang: "cn", value: "该开了"},
		{ personality: 2, phraseName: "openup", lang: "en", value: "Please show your dice!"},
		{ personality: 2, phraseName: "openup", lang: "cn", value: "请开吧!"},
		{ personality: 3, phraseName: "openup", lang: "en", value: "Show your dice! Show your dice!"},
		{ personality: 3, phraseName: "openup", lang: "cn", value: "开吧 开吧!"},
		{ personality: 3, phraseName: "openup", lang: "en", value: "Let's see your dice!"},
		{ personality: 3, phraseName: "openup", lang: "cn", value: "开吧!"},
		{ personality: 4, phraseName: "openup", lang: "en", value: "Let us reveal all."},
		{ personality: 4, phraseName: "openup", lang: "cn", value: "大家开吧"},
		{ personality: 4, phraseName: "openup", lang: "en", value: "I'd like to see the dice. Open up, please."},
		{ personality: 4, phraseName: "openup", lang: "cn", value: "我想看骰子. 请开!"},
		{ personality: 5, phraseName: "openup", lang: "en", value: "I just don't believe you. Open up!"},
		{ personality: 5, phraseName: "openup", lang: "cn", value: "就是不相信你. 开!"},
		{ personality: 5, phraseName: "openup", lang: "en", value: "You're such a liar. Show your damn dice!"},
		{ personality: 5, phraseName: "openup", lang: "cn", value: "太狡猾了. 他妈的开!"},
		{ personality: 1, phraseName: "win", lang: "en", value: "Looks like I've won! Please have a drink."},
		{ personality: 1, phraseName: "win", lang: "cn", value: "看来我赢了! 请喝酒!"},
		{ personality: 1, phraseName: "win", lang: "en", value: "I was lucky!"},
		{ personality: 1, phraseName: "win", lang: "cn", value: "侥幸而已!"},
		{ personality: 2, phraseName: "win", lang: "en", value: "I win! Drink, drink, drink!"},
		{ personality: 2, phraseName: "win", lang: "cn", value: "我赢了! 喝. 喝. 喝!"},
		{ personality: 2, phraseName: "win", lang: "en", value: "I win! Drink up!"},
		{ personality: 2, phraseName: "win", lang: "cn", value: "我赢了! 喝酒!"},
		{ personality: 3, phraseName: "win", lang: "en", value: "Looks like you've lost, darling. Have a drink!"},
		{ personality: 3, phraseName: "win", lang: "cn", value: "亲爱的 看来你输了, 喝酒吧!"},
		{ personality: 3, phraseName: "win", lang: "en", value: "Awww, are you losing to me on purpose?"},
		{ personality: 3, phraseName: "win", lang: "cn", value: "你故意输给我的是吗?"},
		{ personality: 4, phraseName: "win", lang: "en", value: "You've lost this round. Have a drink!"},
		{ personality: 4, phraseName: "win", lang: "cn", value: "你输了. 请喝!"},
		{ personality: 4, phraseName: "win", lang: "en", value: "Have a drink. Take it easy, then continue."},
		{ personality: 4, phraseName: "win", lang: "cn", value: "喝喝酒 慢慢来."},
		{ personality: 5, phraseName: "win", lang: "en", value: "Told you, you're not in my class!"},
		{ personality: 5, phraseName: "win", lang: "cn", value: "都说了你不够资格!"},
		{ personality: 5, phraseName: "win", lang: "en", value: "You had enough yet?"},
		{ personality: 5, phraseName: "win", lang: "cn", value: "输够了没?"},	
		{ personality: 1, phraseName: "lose", lang: "en", value: "Does this mean I lose?"},
		{ personality: 1, phraseName: "lose", lang: "cn", value: "我这算是输了吗?"},
		{ personality: 1, phraseName: "lose", lang: "en", value: "Please be gentle! I'll drink."},
		{ personality: 1, phraseName: "lose", lang: "cn", value: "温柔点! 我喝."},
		{ personality: 2, phraseName: "lose", lang: "en", value: "Rascal! You're bullying me!"},
		{ personality: 2, phraseName: "lose", lang: "cn", value: "坏蛋! 你欺负人"},
		{ personality: 2, phraseName: "lose", lang: "en", value: "You're so annoying! You really go all out!"},
		{ personality: 2, phraseName: "lose", lang: "cn", value: "真讨厌! 真够角清!"},
		{ personality: 3, phraseName: "lose", lang: "en", value: "Baby, you beat me."},
		{ personality: 3, phraseName: "lose", lang: "cn", value: "宝贝 你赢了"},
		{ personality: 3, phraseName: "lose", lang: "en", value: "Darling, you're truly an amazing player."},
		{ personality: 3, phraseName: "lose", lang: "cn", value: "亲爱的 你是个好对手"},
		{ personality: 4, phraseName: "lose", lang: "en", value: "Looks like I lost this round."},
		{ personality: 4, phraseName: "lose", lang: "cn", value: "看来我输了"},
		{ personality: 4, phraseName: "lose", lang: "en", value: "I lost! I'll drink."},
		{ personality: 4, phraseName: "lose", lang: "cn", value: "我输了! 我喝."},
		{ personality: 5, phraseName: "lose", lang: "en", value: "Kid, you're good."},
		{ personality: 5, phraseName: "lose", lang: "cn", value: "小子 你真有一手"},
		{ personality: 5, phraseName: "lose", lang: "en", value: "You got lucky!"},
		{ personality: 5, phraseName: "lose", lang: "cn", value: "算你走运!"},	
		{ personality: 1, phraseName: "stagewin", lang: "en", value: "I can't believe I won!"},
		{ personality: 1, phraseName: "stagewin", lang: "cn", value: ""},
		{ personality: 1, phraseName: "stagewin", lang: "en", value: "Thank you for going easy on me!"},
		{ personality: 1, phraseName: "stagewin", lang: "cn", value: ""},
		{ personality: 2, phraseName: "stagewin", lang: "en", value: "Yayyyyy I win!"},
		{ personality: 2, phraseName: "stagewin", lang: "cn", value: ""},
		{ personality: 2, phraseName: "stagewin", lang: "en", value: "I win! Thanks for the game."},
		{ personality: 2, phraseName: "stagewin", lang: "cn", value: ""},
		{ personality: 3, phraseName: "stagewin", lang: "en", value: "I think you've lost enough tonight, handsome!"},
		{ personality: 3, phraseName: "stagewin", lang: "cn", value: ""},
		{ personality: 3, phraseName: "stagewin", lang: "en", value: "Aww honey, are you too drunk to continue?"},
		{ personality: 3, phraseName: "stagewin", lang: "cn", value: ""},
		{ personality: 4, phraseName: "stagewin", lang: "en", value: "Thanks for playing. I enjoyed it!"},
		{ personality: 4, phraseName: "stagewin", lang: "cn", value: ""},
		{ personality: 4, phraseName: "stagewin", lang: "en", value: "You did your best. Come back next time!"},
		{ personality: 4, phraseName: "stagewin", lang: "cn", value: ""},
		{ personality: 5, phraseName: "stagewin", lang: "en", value: "Come back when you're ready, kid."},
		{ personality: 5, phraseName: "stagewin", lang: "cn", value: ""},
		{ personality: 5, phraseName: "stagewin", lang: "en", value: "You're an embarrassment. Get out of here!"},
		{ personality: 5, phraseName: "stagewin", lang: "cn", value: ""},
		{ personality: 1, phraseName: "stagelose", lang: "en", value: "Oh, I think I drank too much..."},
		{ personality: 1, phraseName: "stagelose", lang: "cn", value: ""},
		{ personality: 1, phraseName: "stagelose", lang: "en", value: "You're too good at this! I can't beat you."},
		{ personality: 1, phraseName: "stagelose", lang: "cn", value: ""},
		{ personality: 2, phraseName: "stagelose", lang: "en", value: "What?! I lost?! This can't be!"},
		{ personality: 2, phraseName: "stagelose", lang: "cn", value: ""},
		{ personality: 2, phraseName: "stagelose", lang: "en", value: "Oh no... I can't play anymore. I'm too drunk!"},
		{ personality: 2, phraseName: "stagelose", lang: "cn", value: ""},
		{ personality: 3, phraseName: "stagelose", lang: "en", value: "Darling, you're too powerful. I give up!"},
		{ personality: 3, phraseName: "stagelose", lang: "cn", value: ""},
		{ personality: 3, phraseName: "stagelose", lang: "en", value: "Darling, you're truly an amazing player."},
		{ personality: 3, phraseName: "stagelose", lang: "cn", value: ""},
		{ personality: 4, phraseName: "stagelose", lang: "en", value: "You are very good. I lose!"},
		{ personality: 4, phraseName: "stagelose", lang: "cn", value: ""},
		{ personality: 4, phraseName: "stagelose", lang: "en", value: "It was a good game. Thank you!"},
		{ personality: 4, phraseName: "stagelose", lang: "cn", value: ""},
		{ personality: 5, phraseName: "stagelose", lang: "en", value: "I don't believe this! How could I have lost to you?!"},
		{ personality: 5, phraseName: "stagelose", lang: "cn", value: ""},
		{ personality: 5, phraseName: "stagelose", lang: "en", value: "I was off-form today. You won't be so lucky next time!"},
		{ personality: 5, phraseName: "stagelose", lang: "cn", value: ""}
	];

	let match = phrases.filter((x)=> { return (x.phraseName === phraseName && x.lang === lang && (x.personality == null || x.personality === personality)); });

	if (match.length === 0) return "";
	if (match.length > 1) {
		var r = Math.floor(Math.random() * match.length);
		return match[r].value;
	}

	return match[0].value;
}

export default GetPhrases;	